### ISSUE TITLE
Themeing

### ISSUE THREAD

**Issue by johnmck95** [SENG480a-NutriDine/mobile#2]
- Pick a colour palette for consistent brand image
- Look into chakraui or mui themes that can be pulled from the provider for easy implementation

**Comment by mehradadimi** [comment]
Difficulty using MUI and Chakra. They can't be used really! There are other component libraries such as React Native Paper that we can use.

**Comment by salamf** [comment]
I'd suggest not using any premade components and making our own. I can create the components if you guys don't want to, it's just better overall to use our own components because then we have more control over them, and its easier to keep their styles consistent with the rest of the project.

**Comment by johnmck95** [comment]
Imo, having an out-of-the-box solution that is already consistent that developers just need to prop pass a couple selections like the colour from our theme provider sounds pretty ideal. Not sure how long it would take to make our own components in React Native, (especially since there isn't a DOM or global CSS). 

If you want to take it on @salamf I think we're going to need components ASAP so we can start building milestone 1 (in particular the form for food input)

**Comment by mehradadimi** [comment]
> Imo, having an out-of-the-box solution that is already consistent that developers just need to prop pass a couple selections like the colour from our theme provider sounds pretty ideal. Not sure how long it would take to make our own components in React Native, (especially since there isn't a DOM or global CSS).
> 
> If you want to take it on @salamf I think we're going to need components ASAP so we can start building milestone 1 (in particular the form for food input)

I personally think using component libraries is significantly faster and less error-prone. Making our own components would be needed If we can't customize the existing ones.

**Comment by mehradadimi** [comment]
Anyway, i think this issue must be used for handling the theme of the app and not the library components. I will link this with the PR that I will have up for automatic theme
