### ISSUE TITLE
Deploy App

### ISSUE THREAD

**Issue by johnmck95** [SENG480a-NutriDine/mobile#8]
Use a hosting service like Expo, Netlify or GitHub pages to host our application. Ideally, it is constantly deployed based on latest main

**Comment by mehradadimi** [comment]
addressed in https://github.com/SENG480a-NutriDine/mobile/issues/10

**Comment by mehradadimi** [comment]
Created a shared expo account:

username: startupprogramming2024
password: startupprogramming2024@@
